version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install libavahi-compat-libdnssd-dev
      - checkout
      - run: npm install
      - run: npm run gulp
      - store_artifacts:
          path: docs
      - run: npm run tpip
      - store_artifacts:
          path: tpip.csv
      - persist_to_workspace:
          root: ../
          paths:
            - project

  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - attach_workspace:
          at: ../
      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: git config --global user.name monty-bot
      - run: git config --global user.email monty-bot@arm.com
      - run: git add --force lib types docs
      - run: git stash save
      - run: git checkout build
      - run: git merge master --no-commit
      - run: git checkout stash -- .
      - run: git commit --allow-empty --message "Automatic Deployment [skip ci]"
      - run: git push

workflows:
  version: 2
  commit:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
